### PR TITLE
Update Turkish Translations

### PR DESCRIPTION
**Pull request by Bartuzen**
Added translation for `command.reload.reloaded`.

### CODE REVIEW

**Comment by BenWoodworth** [comment]
Awesome!! Thank you :)

I'll get this merged in & released hopefully sometime this weekend

**Comment by BenWoodworth** [comment]
I checked some other plugins for how they translated it. Is there a difference between these?
```
konfigürasyon yenilendi
konfigürasyonu yenilendi
```

I ask because [Googling yours only gets 2 results](https://www.google.com/search?q="konfigürasyonu+yenilendi")

**Comment by Bartuzen** [comment]
The correct usage is either `Konfigürasyon yenilendi` or `FastCraft konfigürasyonu yenilendi`. Since we added a subject to the sentence, we need to add `u` to end of `konfigürasyon` word.

**Comment by BenWoodworth** [comment]
Gotcha! Makes sense why the examples I was looking at were the other way. I'll get this merged & released in a bit 🙌

**Pull request merged**
